### ISSUE TITLE
Summery Centre Issue

### ISSUE THREAD

**Issue by ryanxjhan** [techfolios/template-old#46]
The summary shouldn't be left-aligned. I think it should appear in the centre. In the case of one line summary, it could be really ugly. Also if you write multiple lines, there is also a very good chance it appears asymmetrical. 

Example: https://ryanxjhan.github.io/

**Comment by philipmjohnson** [comment]
I agree that when the summary is short, left alignment doesn't look good. On the other hand, when the summary is long, then center alignment can also not look good.  I suggest that you edit your chosen theme file and add `style= "text-align: center"` to center your short summary string. For theme 1, the line you need to edit is here:

https://github.com/techfolios/template/blob/master/_includes/theme-home-builtin-1.html#L24

Good luck!
